# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
Vagrant.configure("2") do |config|
    # 사용할 가상머신 박스 지정
    config.vm.box = "bento/ubuntu-20.04"
  
    # 가상머신의 호스트 이름 설정
    config.vm.hostname = "ansible-host"
  
    # 가상머신의 IP 주소 설정
    config.vm.network "private_network", type: "dhcp"
  
    # 가상머신의 메모리 및 CPU 설정
    config.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 2
    end
  
    # 가상머신에 Ansible 설치 및 실행
    # config.vm.provision "ansible" do |ansible|
    #   ansible.playbook = "your_ansible_playbook.yml"  # Ansible playbook 파일 경로 지정
    # end
  end
  