apiVersion: v1
kind: Service
metadata:
  name: {{ include "5-pass-values-into-dependency.fullname" . }}
  labels:
    {{- include "5-pass-values-into-dependency.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "5-pass-values-into-dependency.selectorLabels" . | nindent 4 }}
